/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zaUFuEKn9HX
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div key="1" className="bg-gray-50/90">
      <section className="py-12 lg:py-24">
        <div className="container grid items-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-2 lg:text-left xl:gap-10">
          <div className="space-y-4">
            <div className="space-y-2">
              <p className="text-sm font-semibold tracking-wide text-gray-500 sm:text-base md:text-xs/relaxed lg:text-sm/relaxed dark:text-gray-400">
                Introducing
              </p>
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Sarah Johnson</h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Product Designer. UX Enthusiast. Coffee Lover.
              </p>
            </div>
          </div>
          <div className="mx-auto">
            <img
              alt="Avatar"
              className="rounded-full overflow-hidden"
              height="400"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/400",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
        </div>
      </section>
      <section className="py-12 lg:py-24">
        <div className="bg-gray-50/90">
          <section className="py-12 lg:py-24">
            <div className="container grid items-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-2 lg:text-left xl:gap-10">
              <div className="space-y-4">
                <div className="space-y-2">
                  <p className="text-sm font-semibold tracking-wide text-gray-500 sm:text-base md:text-xs/relaxed lg:text-sm/relaxed dark:text-gray-400">
                    Introducing
                  </p>
                  <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Sarah Johnson</h1>
                  <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    Product Designer. UX Enthusiast. Coffee Lover.
                  </p>
                </div>
              </div>
              <div className="mx-auto">
                <img
                  alt="Avatar"
                  className="rounded-full overflow-hidden"
                  height="400"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/400",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
            </div>
          </section>
          <section className="py-12 lg:py-24">
            <div className="container grid items-start gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-3 lg:text-left xl:gap-10">
              <div className="space-y-4 lg:col-span-3 lg:order-2 lg:pr-8">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Portfolio</h2>
                  <p className="text-gray-500 dark:text-gray-400">Projects I ve worked on.</p>
                </div>
                <div className="grid w-full grid-cols-1 gap-6 md:grid-cols-3">
                  <div className="flex flex-col min-h-[200px]">
                    <Link
                      className="inline-flex flex-1 flex-col rounded-lg overflow-hidden transition transform-gpu hover:scale-105"
                      href="#"
                    >
                      <img
                        alt="Project"
                        className="rounded-t-lg object-cover aspect-landscape"
                        height="250"
                        src="/placeholder.svg"
                        width="400"
                      />
                      <div className="p-4 flex-1 flex flex-col justify-center">
                        <h3 className="font-semibold">Project Title</h3>
                        <p className="text-sm text-gray-500 mt-1 dark:text-gray-400">Project Category</p>
                      </div>
                    </Link>
                  </div>
                  <div className="flex flex-col min-h-[200px]">
                    <Link
                      className="inline-flex flex-1 flex-col rounded-lg overflow-hidden transition transform-gpu hover:scale-105"
                      href="#"
                    >
                      <img
                        alt="Project"
                        className="rounded-t-lg object-cover aspect-landscape"
                        height="250"
                        src="/placeholder.svg"
                        width="400"
                      />
                      <div className="p-4 flex-1 flex flex-col justify-center">
                        <h3 className="font-semibold">Project Title</h3>
                        <p className="text-sm text-gray-500 mt-1 dark:text-gray-400">Project Category</p>
                      </div>
                    </Link>
                  </div>
                  <div className="flex flex-col min-h-[200px]">
                    <Link
                      className="inline-flex flex-1 flex-col rounded-lg overflow-hidden transition transform-gpu hover:scale-105"
                      href="#"
                    >
                      <img
                        alt="Project"
                        className="rounded-t-lg object-cover aspect-landscape"
                        height="250"
                        src="/placeholder.svg"
                        width="400"
                      />
                      <div className="p-4 flex-1 flex flex-col justify-center">
                        <h3 className="font-semibold">Project Title</h3>
                        <p className="text-sm text-gray-500 mt-1 dark:text-gray-400">Project Category</p>
                      </div>
                    </Link>
                  </div>
                  <div className="flex flex-col min-h-[200px]">
                    <Link
                      className="inline-flex flex-1 flex-col rounded-lg overflow-hidden transition transform-gpu hover:scale-105"
                      href="#"
                    >
                      <img
                        alt="Project"
                        className="rounded-t-lg object-cover aspect-landscape"
                        height="250"
                        src="/placeholder.svg"
                        width="400"
                      />
                      <div className="p-4 flex-1 flex flex-col justify-center">
                        <h3 className="font-semibold">Project Title</h3>
                        <p className="text-sm text-gray-500 mt-1 dark:text-gray-400">Project Category</p>
                      </div>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className="py-12 lg:py-24">
            <div className="container grid items-start gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-3 lg:text-left xl:gap-10">
              <div className="space-y-4 lg:col-span-2 lg:order-2 lg:pr-8">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Me</h2>
                  <p className="text-gray-500 dark:text-gray-400">Want to work together? Send me a message.</p>
                </div>
                <div className="grid w-full grid-cols-1 gap-6 md:grid-cols-2 md:gap-12">
                  <div className="flex flex-col min-h-[200px]">
                    <div className="font-semibold">Email</div>
                    <div className="text-sm text-gray-500/60 dark:text-gray-400/60">Enter your email</div>
                    <Input placeholder="Email" type="email" />
                  </div>
                  <div className="flex flex-col min-h-[200px]">
                    <div className="font-semibold">Message</div>
                    <div className="text-sm text-gray-500/60 dark:text-gray-400/60">Enter your message</div>
                    <Textarea className="min-h-[150px]" placeholder="Message" />
                  </div>
                  <div className="flex justify-center pt-4">
                    <Button size="lg">Submit</Button>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </section>
      <section className="py-12 lg:py-24">
        <div className="container grid items-start gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-3 lg:text-left xl:gap-10">
          <div className="space-y-4 lg:col-span-2 lg:order-2 lg:pr-8">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Me</h2>
              <p className="text-gray-500 dark:text-gray-400">Want to work together? Send me a message.</p>
            </div>
            <div className="grid w-full grid-cols-1 gap-6 md:grid-cols-2 md:gap-12">
              <div className="flex flex-col min-h-[200px]">
                <div className="font-semibold">Email</div>
                <div className="text-sm text-gray-500/60 dark:text-gray-400/60">Enter your email</div>
                <Input placeholder="Email" type="email" />
              </div>
              <div className="flex flex-col min-h-[200px]">
                <div className="font-semibold">Message</div>
                <div className="text-sm text-gray-500/60 dark:text-gray-400/60">Enter your message</div>
                <Textarea className="min-h-[150px]" placeholder="Message" />
              </div>
            </div>
            <div className="flex justify-center pt-4">
              <Button size="lg">Submit</Button>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
